### ISSUE TITLE
Edge lengths dropped, causing error in adding tips

### ISSUE THREAD

**Issue by flakesw** [jinyizju/S.PhyloMaker#5]
Hi Yi and others,

I've been trying to run S.PhyloMaker() on a my own species list, attached here as a .txt (but it's really a .csv). I get the following errors and warnings:

    Error in if (where <= length(tree$tip.label) && position == 0) { : 
      missing value where TRUE/FALSE needed
    In addition: Warning message:
    In bind.tree(tree, tip, where = where, position = pp) :
      one tree has no branch lengths, they have been ignored

I've tracked down where the error occurs. It's at lines 97/98, where edge lengths are needed for the position argument of `bind.tip()`. But at some point in the for loop, edge lengths get dropped, and `bind.tip()` gets passed a NULL value for `position`. 

This happens at line 102 (the warning message), when new species are added to a genus with multiple members. The call to `bind.tip()` in line 102 does not include a position. I don't know if this expected behavior, but `fastMRCA()` only outputs a node number and not an edge length to pass to `bind.tip()`.   

The same problem also occurs in the equivalent parts of the code for scenario 2, but does not occur when I only use scenario 3. Scenario 3 appears to work just fine and makes a plausible phylogeny. 

Do you have any ideas on fixing or working around this problem? As far as I can tell, we need to have an edge length for the newly added species. But I am a novice to phylogenetic work and I'm not sure where we can estimate an edge length; is there any reason not to use the same edge lengths as congeners?

Thanks,

Sam

[spList_test.txt](https://github.com/jinyizju/S.PhyloMaker/files/1640282/spList_test.txt)

**Comment by jinyizju** [comment]
Hello Sam,

I am trying to repeat your run, will respond to you in more detail later.

Yi

**Comment by jinyizju** [comment]
Hello Sam, 

I ran your species list and produced phylogenies under all three scenarios without meeting an error. 
Please make sure the format of the files you use are correct.

cheers,
Yi

**Comment by jinyizju** [comment]
Hello Sam,

I just found the error you met might be due to the newer versions of "bind.tip ()" function were somehow not compatible with S.PhyloMaker. I ran your species list successfully on R 3.2.4 but into error on R 3.4.3. I solved this and uploaded the updated S.PhyloMaker. I guess you will not meet with the same error again if you run your species list using this new S.PhyloMaker.

cheers,
Yi

**Comment by flakesw** [comment]
Thanks, Yi! It works without a hitch now. I should have guessed some version incompatibility might be the culprit. I appreciate the help!

Sam
